global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "power_forecast"
    static_configs:
      - targets: ["web:8000"]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
